import { Module, ModulesConfig } from '@/types'

export const modulesConfig: ModulesConfig = {
  ventasOperaciones: [
    {
      id: 'portal-vendedores',
      name: 'Portal Vendedores',
      description: 'Acceso al sistema de gestión de vendedores',
      url: 'https://vendedores-lamascotera.com.ar/vendedores/login',
      icon: 'Users',
      isActive: true,
      requiredRole: ['ventas_operaciones', 'admin', 'superadmin'],
    },
    {
      id: 'mi-sucursal',
      name: 'Mi Sucursal',
      description: 'Gestión y métricas de tu sucursal',
      url: null,
      icon: 'Store',
      isActive: false,
      requiredRole: ['ventas_operaciones', 'admin', 'superadmin'],
    },
    {
      id: 'people-care',
      name: 'People Care',
      description: 'Bienestar y atención al equipo',
      url: null,
      icon: 'Heart',
      isActive: false,
      requiredRole: ['ventas_operaciones', 'admin', 'superadmin'],
    },
    {
      id: 'logistica',
      name: 'Logistica',
      description: 'Control de envíos y distribución',
      url: 'https://gerencia.vendedores-lamascotera.com.ar/logistica/',
      icon: 'Truck',
      isActive: true,
      requiredRole: ['ventas_operaciones', 'admin', 'superadmin'],
    },
    {
      id: 'back-ecommerce',
      name: 'Back Ecommerce',
      description: 'Administración de tienda online',
      url: null,
      icon: 'ShoppingCart',
      isActive: false,
      requiredRole: ['ventas_operaciones', 'admin', 'superadmin'],
    },
    {
      id: 'club-mascotera',
      name: 'Club La Mascotera',
      description: 'Programa de fidelización',
      url: 'https://gestion.clublamascotera.com.ar/login',
      icon: 'Award',
      isActive: true,
      requiredRole: ['ventas_operaciones', 'admin', 'superadmin'],
    },
  ],
  adminFranquicias: [
    {
      id: 'dashboard-vendedores',
      name: 'Dashboard Vendedores',
      description: 'Métricas y análisis de ventas',
      url: 'https://gerencia.vendedores-lamascotera.com.ar/vendedores/gerencia-dashboard',
      icon: 'BarChart3',
      isActive: true,
      requiredRole: ['admin', 'superadmin'],
    },
    {
      id: 'compras',
      name: 'Compras',
      description: 'Sistema de gestión de compras',
      url: 'http://66.97.38.95/',
      icon: 'Package',
      isActive: true,
      requiredRole: ['admin', 'superadmin'],
    },
    {
      id: 'finanzas',
      name: 'Finanzas',
      description: 'Control financiero y contable',
      url: 'http://66.97.35.249/finanzas/dashboard',
      icon: 'Wallet',
      isActive: true,
      requiredRole: ['admin', 'superadmin'],
    },
    {
      id: 'auditoria',
      name: 'Auditoria',
      description: 'Control y auditoría interna',
      url: null,
      icon: 'ClipboardCheck',
      isActive: false,
      requiredRole: ['admin', 'superadmin'],
    },
    {
      id: 'impositivo',
      name: 'Impositivo',
      description: 'Gestión tributaria y fiscal',
      url: null,
      icon: 'FileText',
      isActive: false,
      requiredRole: ['admin', 'superadmin'],
    },
    {
      id: 'chatbot',
      name: 'Chatbot',
      description: 'Asistente virtual inteligente',
      url: null,
      icon: 'Bot',
      isActive: false,
      requiredRole: ['admin', 'franquicia', 'superadmin'],
    },
    {
      id: 'mi-franquicia',
      name: 'Mi Franquicia',
      description: 'Panel de gestión de franquicia',
      url: null,
      icon: 'Building2',
      isActive: false,
      requiredRole: ['franquicia', 'admin', 'superadmin'],
    },
  ],
}
